// Psychiatric medicines — salt only, based on Kamta's curated list.
// Structure: each condition → { latest: [], common: [] }
// Each drug: { name, dose, class, defaultTiming, defaultFood, defaultDuration }
// Brand is filled by in-house pharmacy at dispense time.

export const MEDICINES_BY_TIER = {
  "Bipolar Disorder": {
    latest: [],
    common: [
      {
        name: "Lithium",
        dose: "300mg, 450mg",
        class: "Mood stabilizer",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Valproate",
        dose: "250mg, 500mg, 750mg",
        class: "Mood stabilizer",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Lamotrigine",
        dose: "25mg, 50mg, 100mg, 200mg",
        class: "Mood stabilizer",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Carbamazepine",
        dose: "100mg, 200mg, 400mg",
        class: "Mood stabilizer",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Oxcarbazepine",
        dose: "150mg, 300mg, 600mg",
        class: "Mood stabilizer",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  Depression: {
    latest: [
      {
        name: "Vortioxetine",
        dose: "5mg, 10mg, 20mg",
        class: "Multimodal",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Agomelatine",
        dose: "25mg, 50mg",
        class: "Melatonergic",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Desvenlafaxine",
        dose: "50mg, 100mg",
        class: "SNRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Dextromethorphan-Bupropion",
        dose: "45mg/105mg",
        class: "NMDA + NDRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Esketamine",
        dose: "56mg, 84mg nasal",
        class: "NMDA antagonist",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Sertraline",
        dose: "25mg, 50mg, 100mg, 150mg, 200mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Escitalopram",
        dose: "5mg, 10mg, 15mg, 20mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Fluoxetine",
        dose: "20mg, 40mg, 60mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Paroxetine",
        dose: "12.5mg, 25mg, 37.5mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Fluvoxamine",
        dose: "50mg, 100mg, 150mg",
        class: "SSRI",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Venlafaxine",
        dose: "37.5mg, 75mg, 150mg",
        class: "SNRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Duloxetine",
        dose: "20mg, 30mg, 60mg",
        class: "SNRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Bupropion",
        dose: "150mg, 300mg",
        class: "NDRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Mirtazapine",
        dose: "7.5mg, 15mg, 30mg, 45mg",
        class: "NaSSA",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Trazodone",
        dose: "25mg, 50mg, 100mg, 150mg",
        class: "SARI",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Amitriptyline",
        dose: "10mg, 25mg, 50mg, 75mg",
        class: "TCA",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Nortriptyline",
        dose: "10mg, 25mg, 50mg",
        class: "TCA",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Imipramine",
        dose: "25mg, 50mg, 75mg",
        class: "TCA",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Clomipramine",
        dose: "25mg, 50mg, 75mg",
        class: "TCA",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  Antipsychotics: {
    latest: [
      {
        name: "Cariprazine",
        dose: "1.5mg, 3mg, 4.5mg, 6mg",
        class: "3rd-gen antipsychotic",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Lumateperone",
        dose: "42mg",
        class: "Atypical antipsychotic",
        defaultTiming: ["Evening"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Brexpiprazole",
        dose: "1mg, 2mg, 3mg, 4mg",
        class: "3rd-gen antipsychotic",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Risperidone",
        dose: "1mg, 2mg, 3mg, 4mg",
        class: "2nd-gen antipsychotic",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Olanzapine",
        dose: "2.5mg, 5mg, 10mg, 20mg",
        class: "2nd-gen antipsychotic",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Quetiapine",
        dose: "25mg, 50mg, 100mg, 200mg, 300mg, 400mg",
        class: "2nd-gen antipsychotic",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Aripiprazole",
        dose: "5mg, 10mg, 15mg, 20mg, 30mg",
        class: "3rd-gen antipsychotic",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Ziprasidone",
        dose: "20mg, 40mg, 60mg, 80mg",
        class: "2nd-gen antipsychotic",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Paliperidone",
        dose: "3mg, 6mg, 9mg",
        class: "2nd-gen antipsychotic",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Amisulpride",
        dose: "100mg, 200mg, 400mg",
        class: "2nd-gen antipsychotic",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Clozapine",
        dose: "25mg, 50mg, 100mg, 200mg",
        class: "2nd-gen (TRS only)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Lurasidone",
        dose: "20mg, 40mg, 80mg",
        class: "2nd-gen antipsychotic",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Asenapine",
        dose: "5mg, 10mg",
        class: "2nd-gen antipsychotic",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Iloperidone",
        dose: "6mg, 8mg, 10mg, 12mg",
        class: "2nd-gen antipsychotic",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  Insomnia: {
    latest: [
      {
        name: "Suvorexant",
        dose: "10mg, 15mg, 20mg",
        class: "DORA",
        defaultTiming: ["HS"],
        defaultFood: "—",
        defaultDuration: "14 days",
      },
      {
        name: "Lemborexant",
        dose: "5mg, 10mg",
        class: "DORA",
        defaultTiming: ["HS"],
        defaultFood: "—",
        defaultDuration: "14 days",
      },
      {
        name: "Zolpidem",
        dose: "5mg, 10mg",
        class: "Z-drug",
        defaultTiming: ["HS"],
        defaultFood: "Empty stomach",
        defaultDuration: "14 days",
      },
      {
        name: "Zopiclone",
        dose: "3.75mg, 7.5mg",
        class: "Z-drug",
        defaultTiming: ["HS"],
        defaultFood: "—",
        defaultDuration: "14 days",
      },
      {
        name: "Eszopiclone",
        dose: "1mg, 2mg, 3mg",
        class: "Z-drug",
        defaultTiming: ["HS"],
        defaultFood: "—",
        defaultDuration: "14 days",
      },
    ],
    common: [
      {
        name: "Melatonin",
        dose: "3mg, 5mg, 10mg",
        class: "Melatonin",
        defaultTiming: ["Night"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Ramelteon",
        dose: "8mg",
        class: "Melatonin agonist",
        defaultTiming: ["HS"],
        defaultFood: "Empty stomach",
        defaultDuration: "1 month",
      },
      {
        name: "Trazodone",
        dose: "25mg, 50mg, 100mg",
        class: "SARI (low-dose sleep)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Mirtazapine",
        dose: "7.5mg, 15mg",
        class: "NaSSA (low-dose sleep)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Doxepin",
        dose: "3mg, 6mg",
        class: "Low-dose TCA (sleep)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  Migraine: {
    latest: [
      {
        name: "Erenumab",
        dose: "70mg, 140mg inj",
        class: "CGRP mAb",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Fremanezumab",
        dose: "225mg inj",
        class: "CGRP mAb",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Galcanezumab",
        dose: "120mg inj",
        class: "CGRP mAb",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Eptinezumab",
        dose: "100mg, 300mg IV",
        class: "CGRP mAb",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "3 months",
      },
      {
        name: "Rimegepant",
        dose: "75mg",
        class: "Gepant",
        defaultTiming: ["SOS"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Ubrogepant",
        dose: "50mg, 100mg",
        class: "Gepant",
        defaultTiming: ["SOS"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Lasmiditan",
        dose: "50mg, 100mg, 200mg",
        class: "Ditan",
        defaultTiming: ["SOS"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Sumatriptan",
        dose: "25mg, 50mg, 100mg",
        class: "Triptan",
        defaultTiming: ["SOS"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Rizatriptan",
        dose: "5mg, 10mg",
        class: "Triptan",
        defaultTiming: ["SOS"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Zolmitriptan",
        dose: "2.5mg, 5mg",
        class: "Triptan",
        defaultTiming: ["SOS"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Naproxen",
        dose: "250mg, 500mg",
        class: "NSAID",
        defaultTiming: ["SOS"],
        defaultFood: "After food",
        defaultDuration: "7 days",
      },
      {
        name: "Ibuprofen",
        dose: "200mg, 400mg, 600mg",
        class: "NSAID",
        defaultTiming: ["SOS"],
        defaultFood: "After food",
        defaultDuration: "7 days",
      },
      {
        name: "Propranolol",
        dose: "20mg, 40mg, 80mg",
        class: "Beta-blocker (prophylaxis)",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Flunarizine",
        dose: "5mg, 10mg",
        class: "Ca blocker (prophylaxis)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Topiramate",
        dose: "25mg, 50mg, 100mg",
        class: "Anticonvulsant (prophylaxis)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Valproate",
        dose: "250mg, 500mg, 750mg",
        class: "Anticonvulsant (prophylaxis)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Amitriptyline",
        dose: "10mg, 25mg",
        class: "TCA (prophylaxis)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  Epilepsy: {
    latest: [
      {
        name: "Brivaracetam",
        dose: "25mg, 50mg, 100mg",
        class: "SV2A modulator",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Perampanel",
        dose: "2mg, 4mg, 6mg, 8mg",
        class: "AMPA antagonist",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Lacosamide",
        dose: "50mg, 100mg, 150mg, 200mg",
        class: "Na-channel (slow)",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Cenobamate",
        dose: "12.5mg, 25mg, 50mg, 100mg, 200mg",
        class: "Na-channel + GABA",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Eslicarbazepine",
        dose: "400mg, 600mg, 800mg",
        class: "Na-channel blocker",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Levetiracetam",
        dose: "250mg, 500mg, 750mg, 1000mg",
        class: "SV2A modulator",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Valproate",
        dose: "250mg, 500mg, 750mg",
        class: "Broad-spectrum AED",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Carbamazepine",
        dose: "100mg, 200mg, 400mg",
        class: "Na-channel blocker",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Oxcarbazepine",
        dose: "150mg, 300mg, 600mg",
        class: "Na-channel blocker",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Lamotrigine",
        dose: "25mg, 50mg, 100mg, 200mg",
        class: "Na-channel blocker",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Phenytoin",
        dose: "50mg, 100mg",
        class: "Na-channel blocker",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Phenobarbital",
        dose: "30mg, 60mg, 100mg",
        class: "Barbiturate",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Topiramate",
        dose: "25mg, 50mg, 100mg",
        class: "Multi-mechanism AED",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Clobazam",
        dose: "5mg, 10mg, 20mg",
        class: "Benzodiazepine",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  OCD: {
    latest: [
      {
        name: "Memantine",
        dose: "5mg, 10mg",
        class: "NMDA antagonist (augment)",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Aripiprazole",
        dose: "5mg, 10mg",
        class: "Augmentation (atypical)",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Risperidone",
        dose: "1mg, 2mg",
        class: "Augmentation (atypical)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Fluoxetine",
        dose: "20mg, 40mg, 60mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Fluvoxamine",
        dose: "50mg, 100mg, 150mg, 200mg",
        class: "SSRI",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Sertraline",
        dose: "50mg, 100mg, 150mg, 200mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Paroxetine",
        dose: "12.5mg, 25mg, 37.5mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Escitalopram",
        dose: "10mg, 20mg, 30mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Clomipramine",
        dose: "25mg, 50mg, 75mg",
        class: "TCA (OCD-specific)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  ADHD: {
    latest: [
      {
        name: "Viloxazine",
        dose: "100mg, 150mg, 200mg",
        class: "SNRI (non-stimulant)",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Lisdexamfetamine",
        dose: "30mg, 50mg, 70mg",
        class: "Stimulant (prodrug)",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Methylphenidate",
        dose: "5mg, 10mg, 18mg, 27mg, 36mg",
        class: "Stimulant",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Atomoxetine",
        dose: "10mg, 18mg, 25mg, 40mg, 60mg",
        class: "Non-stimulant (NRI)",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Clonidine",
        dose: "0.1mg, 0.2mg",
        class: "Non-stimulant (α2)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Guanfacine",
        dose: "1mg, 2mg, 3mg, 4mg",
        class: "Non-stimulant (α2A)",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  PTSD: {
    latest: [
      {
        name: "Prazosin",
        dose: "1mg, 2mg, 5mg",
        class: "α1 blocker (nightmares)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Doxazosin",
        dose: "1mg, 2mg, 4mg",
        class: "α1 blocker (nightmares)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Aripiprazole",
        dose: "5mg, 10mg, 15mg",
        class: "Augmentation (atypical)",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Quetiapine",
        dose: "25mg, 50mg, 100mg, 200mg",
        class: "Augmentation (atypical)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Sertraline",
        dose: "50mg, 100mg, 150mg, 200mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Paroxetine",
        dose: "20mg, 40mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Fluoxetine",
        dose: "20mg, 40mg, 60mg",
        class: "SSRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Venlafaxine",
        dose: "75mg, 150mg",
        class: "SNRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  "Alcohol Use Disorder": {
    latest: [
      {
        name: "Nalmefene",
        dose: "18mg",
        class: "Opioid modulator",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Naltrexone XR",
        dose: "380mg inj",
        class: "Opioid antagonist (LAI)",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Naltrexone",
        dose: "50mg",
        class: "Opioid antagonist",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Acamprosate",
        dose: "333mg",
        class: "Anti-craving",
        defaultTiming: ["Morning", "Afternoon", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Disulfiram",
        dose: "250mg, 500mg",
        class: "Aversive",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  "Opioid Use Disorder": {
    latest: [
      {
        name: "Buprenorphine XR",
        dose: "100mg, 300mg inj",
        class: "Partial agonist (LAI)",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Naltrexone XR",
        dose: "380mg inj",
        class: "Opioid antagonist (LAI)",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Buprenorphine",
        dose: "2mg, 8mg",
        class: "Partial agonist",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Methadone",
        dose: "5mg, 10mg",
        class: "Full agonist (OST)",
        defaultTiming: ["Morning"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Naltrexone",
        dose: "50mg",
        class: "Opioid antagonist",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  "Nicotine Dependence": {
    latest: [
      {
        name: "Varenicline",
        dose: "0.5mg, 1mg",
        class: "Partial nAChR agonist",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "3 months",
      },
    ],
    common: [
      {
        name: "Nicotine replacement therapy",
        dose: "2mg, 4mg gum / patch",
        class: "NRT",
        defaultTiming: ["SOS"],
        defaultFood: "—",
        defaultDuration: "3 months",
      },
      {
        name: "Bupropion",
        dose: "150mg, 300mg",
        class: "NDRI (cessation)",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "3 months",
      },
    ],
  },

  "Cannabis Use": {
    latest: [],
    common: [
      {
        name: "Gabapentin",
        dose: "100mg, 300mg, 400mg",
        class: "Ca ligand",
        defaultTiming: ["Morning", "Afternoon", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "N-acetylcysteine",
        dose: "600mg, 1200mg",
        class: "Glutamate modulator",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  "Stimulant Use": {
    latest: [],
    common: [
      {
        name: "Bupropion",
        dose: "150mg, 300mg",
        class: "NDRI",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Modafinil",
        dose: "100mg, 200mg",
        class: "Wakefulness agent",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },

  "Loss of Libido (Herbal)": {
    latest: [
      {
        name: "Tongkat Ali",
        dose: "200mg, 400mg",
        class: "Herbal",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Maca root",
        dose: "500mg, 1000mg",
        class: "Herbal",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Panax ginseng",
        dose: "200mg, 400mg",
        class: "Herbal",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Ginkgo biloba",
        dose: "40mg, 60mg, 120mg",
        class: "Herbal",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Tribulus terrestris",
        dose: "250mg, 500mg",
        class: "Herbal",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
    common: [
      {
        name: "Ashwagandha",
        dose: "300mg, 500mg",
        class: "Herbal",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Shilajit",
        dose: "250mg, 500mg",
        class: "Herbal",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Safed Musli",
        dose: "500mg",
        class: "Herbal",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Kaunch Beej",
        dose: "500mg",
        class: "Herbal",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Shatavari",
        dose: "500mg",
        class: "Herbal",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Gokshura",
        dose: "500mg",
        class: "Herbal",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },
  Benzodiazepines: {
    latest: [
      {
        name: "Etizolam",
        dose: "0.25mg, 0.5mg, 1mg",
        class: "Benzodiazepine (anxiolytic)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "7 days",
      },
    ],
    common: [
      {
        name: "Clonazepam",
        dose: "0.25mg, 0.5mg, 1mg, 2mg",
        class: "Benzodiazepine",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "7 days",
      },
      {
        name: "Lorazepam",
        dose: "1mg, 2mg",
        class: "Benzodiazepine",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "5 days",
      },
      {
        name: "Alprazolam",
        dose: "0.25mg, 0.5mg, 1mg",
        class: "Benzodiazepine",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "7 days",
      },
      {
        name: "Diazepam",
        dose: "2mg, 5mg, 10mg",
        class: "Benzodiazepine",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "5 days",
      },
      {
        name: "Chlordiazepoxide",
        dose: "10mg, 25mg",
        class: "Benzodiazepine (alcohol withdrawal)",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "7 days",
      },
      {
        name: "Nitrazepam",
        dose: "5mg, 10mg",
        class: "Benzodiazepine (hypnotic)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "7 days",
      },
    ],
  },

  Adjuncts: {
    latest: [],
    common: [
      {
        name: "Pantoprazole",
        dose: "40mg",
        class: "PPI (GI)",
        defaultTiming: ["Morning"],
        defaultFood: "Before food",
        defaultDuration: "1 month",
      },
      {
        name: "Rabeprazole",
        dose: "20mg",
        class: "PPI (GI)",
        defaultTiming: ["Morning"],
        defaultFood: "Before food",
        defaultDuration: "1 month",
      },
      {
        name: "Esomeprazole",
        dose: "40mg",
        class: "PPI (GI)",
        defaultTiming: ["Morning"],
        defaultFood: "Before food",
        defaultDuration: "1 month",
      },
      {
        name: "Ondansetron",
        dose: "4mg, 8mg",
        class: "Antiemetic (GI)",
        defaultTiming: ["SOS"],
        defaultFood: "—",
        defaultDuration: "7 days",
      },
      {
        name: "Domperidone",
        dose: "10mg",
        class: "Antiemetic (GI)",
        defaultTiming: ["SOS"],
        defaultFood: "Before food",
        defaultDuration: "7 days",
      },
      {
        name: "Lactulose",
        dose: "10ml, 15ml syrup",
        class: "Laxative (GI)",
        defaultTiming: ["Night"],
        defaultFood: "—",
        defaultDuration: "1 month",
      },
      {
        name: "Isabgol",
        dose: "5g, 10g",
        class: "Laxative (GI)",
        defaultTiming: ["Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Trihexyphenidyl",
        dose: "2mg",
        class: "Anticholinergic (EPS)",
        defaultTiming: ["Morning", "Night"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Thiamine",
        dose: "100mg",
        class: "Vitamin B1 (AUD)",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "B-complex",
        dose: "1 tab",
        class: "Vitamin",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Folate",
        dose: "5mg",
        class: "Vitamin (pregnancy/Valproate)",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
      {
        name: "Methylcobalamin",
        dose: "500mcg, 1500mcg",
        class: "Vitamin B12",
        defaultTiming: ["Morning"],
        defaultFood: "After food",
        defaultDuration: "1 month",
      },
    ],
  },
};

// --- Backward-compatible exports (for schema.js, pharmacy, api routes, PrintView etc.) ---
// Flat: { [condition]: [{name, dose, class}, ...] }  — merges latest + common
export const MEDICINES_BY_CONDITION = Object.fromEntries(
  Object.entries(MEDICINES_BY_TIER).map(([cond, { latest, common }]) => [
    cond,
    [...latest, ...common].map((m) => ({
      name: m.name,
      dose: m.dose,
      class: m.class,
    })),
  ]),
);

export const CONDITIONS = Object.keys(MEDICINES_BY_TIER);

// Helper: find default timing/food/duration for a given salt name (first match across all conditions)
export function getMedicineDefaults(salt) {
  const base = (salt || "").toLowerCase().trim();
  if (!base) return null;
  for (const cond of CONDITIONS) {
    const { latest, common } = MEDICINES_BY_TIER[cond];
    const hit = [...latest, ...common].find(
      (m) => m.name.toLowerCase() === base,
    );
    if (hit) {
      return {
        timing: hit.defaultTiming || [],
        food: hit.defaultFood || "After food",
        duration: hit.defaultDuration || "7 days",
      };
    }
  }
  return null;
}
